# Generated by Django 2.0.9 on 2018-12-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureur',
            name='rugnummer',
            field=models.IntegerField(default=1),
        ),
    ]
