# Generated by Django 2.0.9 on 2018-12-18 16:37

from django.db import migrations, models
import timeteam.models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0002_coureur_rugnummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureur',
            name='rugnummer',
            field=models.IntegerField(default=timeteam.models.Coureur.number, unique=True),
        ),
    ]
