# Generated by Django 2.0.9 on 2018-12-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0003_auto_20181218_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='promotie_code',
            field=models.CharField(default='1e en 2e => FA, overige => FB', max_length=200),
            preserve_default=False,
        ),
    ]
