# Generated by Django 2.0.9 on 2018-12-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0004_race_promotie_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='deelnemers',
            field=models.ManyToManyField(blank=True, to='timeteam.Coureur'),
        ),
        migrations.AlterField(
            model_name='race',
            name='promotie_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
