# Generated by Django 2.0.9 on 2018-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0005_auto_20181219_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['volgorde']},
        ),
        migrations.AddField(
            model_name='race',
            name='volgorde',
            field=models.IntegerField(default=10),
        ),
    ]
