# Generated by Django 2.1.4 on 2018-12-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0007_auto_20181219_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultaat',
            name='split2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultaat',
            name='split3',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='resultaat',
            name='split4',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='resultaat',
            name='split1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='resultaat',
            name='totaal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
