# Generated by Django 2.1.4 on 2018-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0010_auto_20181219_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultaat',
            name='split1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultaat',
            name='split2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultaat',
            name='split3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultaat',
            name='split4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
