# Generated by Django 2.1.4 on 2018-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeteam', '0012_auto_20181219_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bepaling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regel', models.TextField()),
            ],
        ),
    ]
